language: go

dist: trusty
sudo: false

go:
  - 1.8.x

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test $(go list ./... | grep -v /vendor/)
  - go build
  - tar -czf gdc-client_${TRAVIS_TAG}_${GOOS}_${GOARCH}.tar.gz gdc-client

deploy:
  provider: releases

  api_key:
    secure: QcdIF354Xje4YmKDQkZ3gnFcTLJqShJYMnlbldhhK2XI7J42tMMugzTVbAeNDU5Dg/2mAjJMwcR6u0kFcEjL515fg5W4US51C5efNzp9cdtNaXunxaLaUV8DIM0GCeNIGSFIlaW7DA0U4PFi5eJSW8QDW3qd4qpwOeT9/mUZwymshMuJ6mpu8KNcLws/e22YM3OKHuoqYs5uhgBgnotgL06dRDHcnJ4F83TKJzjmPP8txuHolO6Goad2bjw1Z6S8Tv/PYIz5PTcx1ziyL7sD0rT71cE2UBALEEWuMaAcZ3oelYDYNX3hppvOyiG3CIfo3eizQQ70ljpNBbGMbm1yzuEnq7mcCxLw63a5tag6HJA9RQI7LrKnQScXPBDjOL70PWjCyxTeg0/pEoIOFM39mNvhrFQexK76xjFhroydWnsGTQ53/aM5cgizAzIIONNThVWGs4BqzFpf1h5HHC1CWcFbFULaQ7d/XxciBaHudCXIawo78pmaJWa75Eu2RAjn06FbVkpILScWKGGuiV5QEmX8V1oPmTakBIl9c6C82OP7rlViZRiPwR+IjRoV3w12Dyh0wA8E2NitiY72F5IvcyFPV3nkfj0LxoY+MFmepAH3CBsplbJMIdctfc5974QfUPViXzx3MU/lCAk2ulmMN8zsZOd7Zm8OrU2sxCuOj/8=

  skip_cleanup: true
  file: gdc-client_${TRAVIS_TAG}_${GOOS}_${GOARCH}.tar.gz

  on:
    repo: gudCodes/gdc-client
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
