language: go

dist: trusty
sudo: false

go:
  - 1.13.x

env:
  - BUILD_GOOS=linux BUILD_GOARCH=amd64
  - BUILD_GOOS=linux BUILD_GOARCH=386
  - BUILD_GOOS=linux BUILD_GOARCH=arm
  - BUILD_GOOS=darwin BUILD_GOARCH=amd64
  - BUILD_GOOS=darwin BUILD_GOARCH=386

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test $(go list ./... | grep -v /vendor/)
  - CGO_ENABLED=0 GOOS=${BUILD_GOOS} GOARCH=${BUILD_GOARCH} go build -ldflags "-extldflags '-static' -X 'github.com/MurphyMarkW/gdc-client/client.Version=$(git tag --points-at HEAD)'"

before_deploy:
  - tar -czf gdc-client_${TRAVIS_TAG}_${BUILD_GOOS}_${BUILD_GOARCH}.tar.gz gdc-client

deploy:
  provider: releases

  api_key:
    secure: TTgr80M1yfSRlDAh9ZR7THB4kFDslrbUgSqG/v/ET4HSzuCoEzJ+eKXUdakAgsSsm0xIcR1wu6tVvvz80NOi8FYuhe74IfWrx9aBhJgMn/fYhImuZ1zGoIxGi6Guzz+w9EqxmgtVK1JLJbuov4CF8vbFqg7ZbHxZlSHhpwgKUR5TpXVFrSwGci7NeC3ivbjCFO0zeLI2O4osPTELhZjIjhVbMlcLd9lG9M+qVkufN56ur3ieoZhcrwRYm56Ig8zr0zNLMCfZOzzk+vBTMZKyMcBNPbGTHwHTTSf/5TS4xUZvoJLCSl7Z2nDKT9P8hs23V0z671wcczA3xguyHAJN5LMorqU3+7F/NCuI+WWCXkb5gUYVUYSAYQDURTP0kfp6b2uKeuESQMeRHe3vaHuwo2oaqD6ZFol0XhChm38UzXM2dSMlZeWxxJlh3tNxIVnHlOMw8aLyX4eR8qTc5Mi13xwfahZR/efaI19Rl1jii0OgDTN/FQOUyq39bHjJ1jS28f9WeLZGLDg9R1LCQ+1tcRRKXdyWK+Vh6fCQF+a8errncbkFRe0yrFIwlD84NpByWbITst0tBLnytCl4VgiEw2q5xyJpE60S9hdjlvFDrtj15gg+kUzI1robJdLEVP5pto5LQpNMZz202PNJnaskbD7KToTxP4kekTTN2XE17Xw=

  skip_cleanup: true
  overwrite: true
  file: gdc-client_${TRAVIS_TAG}_${BUILD_GOOS}_${BUILD_GOARCH}.tar.gz

  on:
    repo: MurphyMarkW/gdc-client
    tags: true
